version: '3.8'

services:
  creacion_imagen:
    build:
      context: .
      dockerfile: DockerfileApache_hossam
    image: hossam-apache-image:p1
    scale: 0
    networks:
      - red_web
      - red_servicios

  web1:
    image: hossam-apache-image:p1
    container_name: web1
    volumes:
      - ./web_hossam:/var/www/html
    ports:
      - "8081:80"
    networks:
      red_web: 
        ipv4_address: 192.168.10.2
      red_servicios:
        ipv4_address: 192.168.20.2

  web2:
    image: hossam-apache-image:p1
    container_name: web2
    volumes:
      - ./web_hossam:/var/www/html
    ports:
      - "8082:80"
    networks:
      red_web: 
        ipv4_address: 192.168.10.3

  web3:
    image: hossam-apache-image:p1
    container_name: web3
    volumes:
      - ./web_hossam:/var/www/html
    ports:
      - "8083:80"
    networks:
      red_web: 
        ipv4_address: 192.168.10.4
      red_servicios:
        ipv4_address: 192.168.20.4

  web4:
    image: hossam-apache-image:p1
    container_name: web4
    volumes:
      - ./web_hossam:/var/www/html
    ports:
      - "8084:80"
    networks:
      red_web: 
        ipv4_address: 192.168.10.5
      red_servicios:
        ipv4_address: 192.168.20.5

  web5:
    image: hossam-apache-image:p1
    container_name: web5
    volumes:
      - ./web_hossam:/var/www/html
    ports:
      - "8085:80"
    networks:
      red_web: 
        ipv4_address: 192.168.10.6
      red_servicios:
        ipv4_address: 192.168.20.6

  web6:
    image: hossam-apache-image:p1
    container_name: web6
    volumes:
      - ./web_hossam:/var/www/html
    ports:
      - "8086:80"
    networks:
      red_web: 
        ipv4_address: 192.168.10.7
      red_servicios:
        ipv4_address: 192.168.20.7

  web7:
    image: hossam-apache-image:p1
    container_name: web7
    volumes:
      - ./web_hossam:/var/www/html
    ports:
      - "8087:80"
    networks:
      red_web: 
        ipv4_address: 192.168.10.8
      red_servicios:
        ipv4_address: 192.168.20.8

  web8:
    image: hossam-apache-image:p1
    container_name: web8
    volumes:
      - ./web_hossam:/var/www/html
    ports:
      - "8088:80"
    networks:
      red_web: 
        ipv4_address: 192.168.10.9
      red_servicios:
        ipv4_address: 192.168.20.9

networks:
  red_web:
      name: red_web
      driver: bridge
      ipam:
        config:
          - subnet: 192.168.10.0/24
  red_servicios:
      name: red_servicios
      driver: bridge
      ipam:
        config:
          - subnet: 192.168.20.0/24

