version: '3.9'

services:
  master-hossam:
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H https://192.168.10.50:443/
    networks:
      red_web:
        ipv4_address: 192.168.10.70

  worker-hossam:
    image: locustio/locust
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master-hossam
    depends_on:
      - master-hossam
    deploy:
      replicas: 5
    networks:
      red_web:

networks:
  red_web:
    external: true